services:
  api:
    container_name: webapi
    profiles: ['dev']
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file: .env
    ports:
      - 4600:4600

  tests:
    container_name: tests
    profiles: ['tests']
    build:
      context: .
      dockerfile: ./docker/Dockerfile.test
    env_file: .env
