name: CD

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  release:
    types: [published]

jobs:
  health-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
      VERSION: ${{ github.event.release.tag_name }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ env.VERSION }}

    - name: Install dependencies
      run: npm ci

    # TODO: Add your tests here

  build:
    needs: health-check
    runs-on: ubuntu-latest
    env:
      GOOGLE_PROJECT_ID: ihm-production
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VERSION: ${{ github.event.release.tag_name }}
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{env.VERSION }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        cache: "npm"
        node-version-file: ".nvmrc"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    #TODO: Add your build and push steps here
